# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_refactor_citations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('citation_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_marker', models.CharField(blank=True, max_length=50, null=True)),
                ('page_range', models.TextField(blank=True, null=True)),
                ('classical_identifier', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bibliography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Bibliography')),
            ],
        ),
    ]
