# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_citation'),
    ]

    operations = [
        migrations.RenameField("Stones", "shapefile", "geojson"),
    ]
