# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20180613_2045'),
    ]

    operations = [
        migrations.RenameField("Trees", "shapefile", "geojson"),
    ]
