# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20180615_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoneimages',
            name='stone',
        ),
        migrations.AlterField(
            model_name='stoneimages',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
