# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20180615_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='stones'),
        ),
    ]
