# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_auto_20180615_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneimages',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Stones'),
        ),
    ]
