# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_auto_20180618_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='trees')),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Trees')),
            ],
        ),
        migrations.AlterField(
            model_name='stoneimages',
            name='img',
            field=models.ImageField(null=True, upload_to='stones'),
        ),
    ]
