# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_auto_20180618_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stones',
            old_name='begin_date',
            new_name='start_date',
        ),
    ]
