# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0021_treeedits_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('alternate_name', models.TextField(blank=True, null=True)),
                ('petrographic_details', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
                ('poisson_ratio_low', models.FloatField(blank=True, null=True)),
                ('poisson_ratio_high', models.FloatField(blank=True, null=True)),
                ('absorption', models.FloatField(blank=True, null=True)),
                ('quarry_location', models.TextField(blank=True, null=True)),
                ('archaeological_sources', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dates_of_use', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('dates_notes', models.TextField(blank=True, null=True)),
                ('density_avg', models.FloatField(blank=True, null=True)),
                ('density_low', models.FloatField(blank=True, null=True)),
                ('density_high', models.FloatField(blank=True, null=True)),
                ('elastic_modulus_average', models.FloatField(blank=True, null=True)),
                ('elastic_modulus_low', models.FloatField(blank=True, null=True)),
                ('elastic_modulus_high', models.FloatField(blank=True, null=True)),
                ('rupture_modulus_average', models.FloatField(blank=True, null=True)),
                ('rupture_modulus_low', models.FloatField(blank=True, null=True)),
                ('rupture_modulus_high', models.FloatField(blank=True, null=True)),
                ('compressive_strength_average', models.FloatField(blank=True, null=True)),
                ('compressive_strength_low', models.FloatField(blank=True, null=True)),
                ('compressive_strength_high', models.FloatField(blank=True, null=True)),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Stones')),
            ],
        ),
    ]
