# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0025_auto_20180628_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Bibliography'),
        ),
        migrations.AlterField(
            model_name='citationstone',
            name='bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Bibliography'),
        ),
        migrations.AlterField(
            model_name='citationstone',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Stones'),
        ),
        migrations.AlterField(
            model_name='citationtree',
            name='bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Bibliography'),
        ),
        migrations.AlterField(
            model_name='stoneimages',
            name='stone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Stones'),
        ),
        migrations.AlterField(
            model_name='stones',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treeimages',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Trees'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='common_name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='sci_name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
