# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0026_auto_20180628_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeedits',
            name='citation',
            field=models.FileField(blank=True, null=True, upload_to='trees/edits'),
        ),
    ]
