# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0034_stoneedits_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoneedits',
            name='image',
        ),
        migrations.AddField(
            model_name='treeedits',
            name='image',
            field=models.ImageField(null=True, upload_to='trees/edit-images'),
        ),
    ]
