# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0039_auto_20180713_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoneedits',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='treeedits',
            old_name='img',
            new_name='image',
        ),
    ]
