# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20180613_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='stones',
            name='begin_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stones',
            name='dates_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stones',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
