# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20180615_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='stones')),
            ],
        ),
        migrations.RemoveField(
            model_name='stones',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='image',
        ),
        migrations.AddField(
            model_name='stoneimage',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Stones'),
        ),
    ]
