# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20180615_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoneImage',
            new_name='StoneImages',
        ),
    ]
