# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_remove_stoneimages_stone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoneImages',
        ),
    ]
