# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_stoneimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneimages',
            name='stone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Trees'),
        ),
    ]
