# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_auto_20180618_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneimages',
            name='stone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree.Stones'),
        ),
    ]
