# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_auto_20180620_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stones',
            old_name='poisson_ratio',
            new_name='poisson_ratio_high',
        ),
        migrations.AddField(
            model_name='stones',
            name='poisson_ratio_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
