# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0024_auto_20180628_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationtree',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Trees'),
        ),
    ]
