# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0028_auto_20180629_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneedits',
            name='citation',
            field=models.FileField(blank=True, null=True, upload_to='stones/edits'),
        ),
    ]
