# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0030_auto_20180709_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneedits',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeedits',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
