# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0031_auto_20180711_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneedits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stones/edits'),
        ),
        migrations.AddField(
            model_name='treeedits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trees/edits'),
        ),
    ]
