# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0032_auto_20180713_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoneedits',
            name='image',
        ),
        migrations.RemoveField(
            model_name='treeedits',
            name='image',
        ),
    ]
