# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0035_auto_20180713_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeedits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trees/edit-images'),
        ),
    ]
