# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0037_stoneedits_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoneimages',
            old_name='stone',
            new_name='main_object',
        ),
        migrations.RenameField(
            model_name='treeimages',
            old_name='tree',
            new_name='main_object',
        ),
    ]
