# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0038_auto_20180713_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoneedits',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='treeedits',
            old_name='image',
            new_name='img',
        ),
    ]
