# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0041_auto_20180719_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneimages',
            name='img',
            field=models.ImageField(null=True, upload_to='treestone/tree/static/images/stones'),
        ),
        migrations.AlterField(
            model_name='treeimages',
            name='img',
            field=models.ImageField(null=True, upload_to='treestone/tree/static/images/trees'),
        ),
    ]
