# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0042_auto_20180719_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='bib_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stoneimages',
            name='img',
            field=models.ImageField(null=True, upload_to='images/stones'),
        ),
        migrations.AlterField(
            model_name='treeimages',
            name='img',
            field=models.ImageField(null=True, upload_to='images/trees'),
        ),
    ]
