# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0043_auto_20180719_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneedits',
            name='main_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Stones'),
        ),
        migrations.AlterField(
            model_name='treeedits',
            name='main_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Trees'),
        ),
    ]
